title: "COVID Herd Immunity"

* 'Herd immunity', also known as 'population immunity', is the indirect protection from an infectious disease that happens when a population is immune either through vaccination or immunity developed through previous infection. WHO supports achieving 'herd immunity' through vaccination, not by allowing a disease to spread through any segment of the population, as this would result in unnecessary cases and deaths.
* Herd immunity against COVID-19 should be achieved by protecting people through vaccination, not by exposing them to the pathogen that causes the disease.
*  Vaccines train our immune systems to create proteins that fight disease, known as ‘antibodies’, just as would happen when we are exposed to a disease but – crucially – vaccines work without making us sick. Vaccinated people are protected from getting the disease in question and passing on the pathogen, breaking any chains of transmission.
*  To safely achieve herd immunity against COVID-19, a substantial proportion of a population would need to be vaccinated, lowering the overall amount of virus able to spread in the whole population. One of the aims with working towards herd immunity is to keep vulnerable groups who cannot get vaccinated (e.g. due to health conditions like allergic reactions to the vaccine) safe and protected from the disease. 
*  The percentage of people who need to be immune in order to achieve herd immunity varies with each disease. For example, herd immunity against measles requires about 95% of a population to be vaccinated. The remaining 5% will be protected by the fact that measles will not spread among those who are vaccinated. For polio, the threshold is about 80%. 
*  The proportion of the population that must be vaccinated against COVID-19 to begin inducing herd immunity is not known. This is an important area of research and will likely vary according to the community, the vaccine, the populations prioritized for vaccination, and other factors.

                 
## wish to build my webpage through following steps
* At first consider a small portion of population who need to immune from covid
* consider:
 
- population of the area
- population who are eligible for vaccine  
- population given vaccine(1st dose only and both doses)
- age distribution of vaccinated people
- vulnerable gropus who can not get vaccinated
- types of vaccine
- post covid health issue
- hospitalization 
- daily cases, deaths, recovered data
- infaction rate; ro=number of infections/no of those at risk of infection

#### The lower infaction rate provides information that most people are immune to covid-19
#### Thus we will get herd immunity
#### Need to fix a lower bound to infection rate
#### Need to fix the proportion of the population that must be vaccinate against covid-19 

